version: '2'
services:
  syncthing-relay-discovery:
    image: rdissertori/syncthing-relay-discovery-bluemix
    container_name: syncthing-relay-discovery
    volumes:
      - ./certs/:/home/syncthing/certs/:ro
    ports:
      - "22067:22067"
      - "22026:22026"
      - "22070:22070"
    restart: always